[project]
name = "tool_sdk"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.4",
    "fastapi>=0.119.0",
    "uvicorn>=0.38.0",
    "pydantic>=2.12.3",
    "httpx>=0.27.2",
]
