name: "CI - linters and tests"

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  lint-and-test:
    name: linters and tests
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v5

      - name: "Install just"
        uses: extractions/setup-just@v3

      - name: "Copy .env"
        run: cp .env.example .env

      - name: "Run linters and tests"
        run: just dc all
